tasks:
  - openMode: split-right
    command: gp open readme.scroll
  - openMode: split-right
    command: npm install -g . && scroll build
  - openMode: split-right
    command: python3 -m http.server 3000

ports:
  - port: 3000
    onOpen: open-preview
